<?php

/**
 * @file
 * Contains drup_site.module.
 */

/**
 * Implements ./hooks/*.php
 */
$themeDirectory = __DIR__ . '/hooks';
$dir = scandir($themeDirectory, SCANDIR_SORT_NONE);

foreach ($dir as $filename) {
    $path = $themeDirectory . '/' . $filename;
    $fileExtension = pathinfo($path);

    if (isset($fileExtension['extension']) && $fileExtension['extension'] === 'php' && is_file($path)) {
        require_once $path;
    }
}