<?php

use Drupal\drup\Helper\DrupString;

/**
 * Vue ""
 */
function drup_theme_views_rows_controller__VIEWID($variables) {
    //    if (!empty($variables['view']->result)) {
    //        foreach ($variables['view']->result as $id => &$result) {
    //            // Subtitle
    //            if ($subtitle = $result->drupField->getValue('subtitle', 'value')) {
    //                $result->body = DrupString::truncate($subtitle, 200);
    //            }
    //
    //            // Date
    //            $result->date = \Drupal::service('date.formatter')->format($result->_entity->getCreatedTime(), 'custom', 'd F Y');
    //        }
    //    }
    //
    //    return $variables;
}

/**
 * Vue + Display ""
 */
function drup_theme_views_rows_controller__VIEWID__DISPLAYID($variables) {
//    if (!empty($variables['view']->result)) {
//        foreach ($variables['view']->result as $id => &$result) {
//            // Subtitle
//            if ($subtitle = $result->drupField->getValue('subtitle', 'value')) {
//                $result->body = DrupString::truncate($subtitle, 200);
//            }
//
//            // Date
//            $result->date = \Drupal::service('date.formatter')->format($result->_entity->getCreatedTime(), 'custom', 'd F Y');
//        }
//    }
//
//    return $variables;
}
