######
# Drupal 8 1.5
# @link https://docs.devwithlando.io/tutorials/drupal8.html
######


# Name
name: d8-starter

# Recipe used
recipe: drupal8
config:
  webroot: web
  php: '7.3'
  via: apache
  database: mariadb
  xdebug: false

# Commands on events
events:
  #post-start:
  #- appserver: cd $LANDO_WEBROOT && chown $LANDO_WEBROOT_USER:$LANDO_WEBROOT_GROUP -R .
  #- appserver: echo "alias ll='ls -la'" > ~/.bashrc
  post-db-import:
  - appserver: cd $LANDO_WEBROOT && drush cr -y

# Access
proxy:
  appserver:
  - d8-starter.lndo.site
  mailhog:
  - mail.d8-starter.lndo.site
  pma:
  - pma.d8-starter.lndo.site

# Additional services
services:
  appserver:
    build:
      - composer install
    composer:
      deployer/deployer: '6.*'
  node:
    type: node:11
    globals:
      gulp-cli: "latest"
  mailhog:
    type: mailhog
    hogfrom:
    - appserver
  pma:
    type: phpmyadmin

# Additionnal commands line "lando XXX"
tooling:
  drush:
    cmd: /app/vendor/bin/drush
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  gulp:
    service: node
  dep:
    service: appserver
    description: "Deploy app with deploy.php"
