######
# Drupal 8 1.1
# @see https://docs.devwithlando.io/tutorials/drupal8.html
# @see https://github.com/lando/lando/blob/master/examples/drupal8/.lando.yml
# @see https://docs.devwithlando.io/tutorials/setup-additional-services.html
######


# Name
name: d8-starter

# Recipe used
recipe: drupal8
config:
  webroot: web
  php: '7.2'
  via: apache
  database: mariadb
  drush: composer
  xdebug: false

# Commands on events
events:
  #post-start:
  #- appserver: cd $LANDO_WEBROOT && chown $LANDO_WEBROOT_USER:$LANDO_WEBROOT_GROUP -R .
  #- appserver: echo "alias ll='ls -la'" > ~/.bashrc
  post-db-import:
  - appserver: cd $LANDO_WEBROOT && drush cr -y

# Access
proxy:
  appserver:
  - d8-starter.lndo.site
  mailhog:
  - mail.d8-starter.lndo.site
  pma:
  - pma.d8-starter.lndo.site

# Additional services
services:
  appserver:
    composer:
      deployer/deployer: '6.*'
  node:
    type: node:latest
    globals:
      gulp-cli: "latest"
  mailhog:
    type: mailhog
    hogfrom:
    - appserver
  pma:
    type: phpmyadmin

# Additionnal commands line "lando XXX"
tooling:
  npm:
    service: node
  node:
    service: node
  yarn:
    service: node
  gulp:
    service: node
  dep:
    service: appserver
    description: "Deploy app with deploy.php"
