<?php

/**
 * @file
 * Contains drup_router.module.
 */

Use Drupal\node\Entity\Node;

/**
 * Implements hook_token_info().
 */
function drup_router_token_info() {
    $tokenType = 'drup_router';

    $types[$tokenType] = [
        'name' => t("Custom Routes"),
        'description' => t("Get custom routes slugs from DrupRouter module"),
    ];

    $tokensAvailable = [];
    $drupRouter = \Drupal::service('drup_router.router');
    $routes = $drupRouter->getRoutes();
    if (!empty($routes)) {
        foreach ($routes as $index => $route) {
            $routeName = $route['routeName'];
            $tokensAvailable[$routeName] = [
                'name' => $routeName,
                'description' => 'Slug for ' . $routeName
            ];
        }
    }

    return [
        'types' => $types,
        'tokens' => [
            $tokenType => $tokensAvailable,
        ]
    ];
}

/**
 * Implements hook_tokens().
 */
function drup_router_tokens($type, $tokens, array $data, array $options, \Drupal\Core\Render\BubbleableMetadata $bubbleable_metadata) {
    $tokenType = 'drup_router';

    $replacements = array();
    if ($type === $tokenType) {
        $drupRouter = \Drupal::service('drup_router.router');

        foreach ($tokens as $name => $original) {
            $routeID = $drupRouter->getID($name);
            
            if ($alias = \Drupal::service('path.alias_manager')->getAliasByPath('/node/'.$routeID)) {
                $replacements[$original] = $alias;
            } else {
                $node = Node::load($routeID);
                $replacements[$original] = $node->getTitle();
            }
            break;
        }
    }
    
    return $replacements;
}
