<?php

/**
 * @file
 * Functions to support theming in the drup_theme theme.
 */

/**
 * Load all files in /theme/ directory
 */
$themeDirectory = __DIR__ . '/theme';
$dir = scandir($themeDirectory, SCANDIR_SORT_NONE);

foreach ($dir as $filename) {
    $path = $themeDirectory . '/' . $filename;
    $fileExtension = pathinfo($path);

    if (isset($fileExtension['extension']) && $fileExtension['extension'] === 'inc' && is_file($path)) {
        require_once $path;
    }
}
